export const bookActionTypes = {
    SETBOOKS: "SETBOOKS",
    SELECTEDBOOK: "SELECTEDBOOK",
    REMOVESELECTEDBOOK: "REMOVESELECTEDBOOK",
    ADDTOCART: "ADDTOCART",
    REMOVEFROMCART: "REMOVEFROMCART",
    ADDTOMYORDERS: "ADDTOMYORDERS",
    CLEARCART : "CLEARCART"
}